# Use an official Node.js runtime as the base image
FROM node:14 as build-stage

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object
# Copy the entire frontend directory to the container
COPY . .

# Expose port 3000
EXPOSE 3000

# Start Nginx server
CMD ["npm", "run", "start"]
